export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST'

export const CHANGE_ADDRESS = 'CHANGE_ADDRESS'

export const CHANGE_CURRENT_ADDRESS_INDEX = 'CHANGE_CURRENT_ADDRESS_INDEX'

export const ADD_ADDRESS = 'ADD_ADDRESS'

export const DELETE_ADDRESS = 'DELETE_ADDRESS'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY'

export const DELETE_SEARCH_HISTORY = 'DELETE_SEARCH_HISTORY'

export const SET_TOKEN = 'SET_TOKEN'

export const REMOVE_TOKEN = 'REMOVE_TOKEN'

export const SET_SHOP_CART = 'SET_SHOP_CART'

export const DEL_SLECT_SHOP_CART_ITEM = 'DEL_SLECT_SHOP_CART_ITEM'

export const SET_SHOP_CART_LIST = 'SET_SHOP_CART_LIST'

export const SET_IS_SHOP_CART = 'SET_IS_SHOP_CART'

export const SET_CURRENT_COMMENT_LIST = 'SET_CURRENT_COMMENT_LIST'

export const SET_CURRENT_ORDER_DETAIL = 'SET_CURRENT_ORDER_DETAIL'

export const SET_IS_BUY_GOODS = 'SET_IS_BUY_GOODS'

export const SET_CURRENT_REFUND_GOODS = 'SET_CURRENT_REFUND_GOODS'

export const SET_IN_PAYMENT = 'SET_IN_PAYMENT'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_UNREAD_MESSAGE = 'SET_UNREAD_MESSAGE'

export const REMOVE_UNREAD_MESSAGE = 'REMOVE_UNREAD_MESSAGE'

export const SET_THIRD_LOGIN_INFO = 'SET_THIRD_LOGIN_INFO'

export const REMOVE_THIRD_LOGIN_INFO = 'REMOVE_THIRD_LOGIN_INFO'

